# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: knowledge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'knowledge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fknowledge.proto\x12\x19\x61ssessorflow.knowledge.v1\"\xad\x01\n\x16ProcessMaterialRequest\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontent_text\x18\x02 \x01(\t\x12\x13\n\x0bsource_type\x18\x03 \x01(\t\x12\x13\n\x0bsource_file\x18\x04 \x01(\t\x12\x12\n\nsource_url\x18\x05 \x01(\t\x12\x13\n\x0b\x61ssessor_id\x18\x06 \x01(\t\x12\x15\n\rassessment_id\x18\x07 \x01(\t\"T\n\x17ProcessMaterialResponse\x12\x16\n\x0e\x63hunks_created\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x11\n\tchunk_ids\x18\x03 \x03(\t2\x8c\x01\n\x10KnowledgeService\x12x\n\x0fProcessMaterial\x12\x31.assessorflow.knowledge.v1.ProcessMaterialRequest\x1a\x32.assessorflow.knowledge.v1.ProcessMaterialResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'knowledge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSMATERIALREQUEST']._serialized_start=47
  _globals['_PROCESSMATERIALREQUEST']._serialized_end=220
  _globals['_PROCESSMATERIALRESPONSE']._serialized_start=222
  _globals['_PROCESSMATERIALRESPONSE']._serialized_end=306
  _globals['_KNOWLEDGESERVICE']._serialized_start=309
  _globals['_KNOWLEDGESERVICE']._serialized_end=449
# @@protoc_insertion_point(module_scope)
