# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from validator_agent._grpc import knowledge_pb2 as knowledge__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in knowledge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KnowledgeServiceStub(object):
    """Knowledge Service — Validator Agent uses ProcessMaterial only.
    Full proto at: knowledge-service/proto/assessorflow/knowledge/v1/knowledge.proto
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessMaterial = channel.unary_unary(
                '/assessorflow.knowledge.v1.KnowledgeService/ProcessMaterial',
                request_serializer=knowledge__pb2.ProcessMaterialRequest.SerializeToString,
                response_deserializer=knowledge__pb2.ProcessMaterialResponse.FromString,
                _registered_method=True)


class KnowledgeServiceServicer(object):
    """Knowledge Service — Validator Agent uses ProcessMaterial only.
    Full proto at: knowledge-service/proto/assessorflow/knowledge/v1/knowledge.proto
    """

    def ProcessMaterial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessMaterial': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessMaterial,
                    request_deserializer=knowledge__pb2.ProcessMaterialRequest.FromString,
                    response_serializer=knowledge__pb2.ProcessMaterialResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'assessorflow.knowledge.v1.KnowledgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('assessorflow.knowledge.v1.KnowledgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KnowledgeService(object):
    """Knowledge Service — Validator Agent uses ProcessMaterial only.
    Full proto at: knowledge-service/proto/assessorflow/knowledge/v1/knowledge.proto
    """

    @staticmethod
    def ProcessMaterial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assessorflow.knowledge.v1.KnowledgeService/ProcessMaterial',
            knowledge__pb2.ProcessMaterialRequest.SerializeToString,
            knowledge__pb2.ProcessMaterialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
