# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from validator_agent._grpc import submission_pb2 as submission__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in submission_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SubmissionServiceStub(object):
    """Assessment Submission Service — Validator Agent uses GetMaterials + UpdateMaterialValidation only.
    Full proto at: submission-service/proto/assessorflow/submission/v1/submission.proto
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMaterials = channel.unary_unary(
                '/assessorflow.submission.v1.SubmissionService/GetMaterials',
                request_serializer=submission__pb2.GetMaterialsRequest.SerializeToString,
                response_deserializer=submission__pb2.GetMaterialsResponse.FromString,
                _registered_method=True)
        self.UpdateMaterialValidation = channel.unary_unary(
                '/assessorflow.submission.v1.SubmissionService/UpdateMaterialValidation',
                request_serializer=submission__pb2.UpdateMaterialValidationRequest.SerializeToString,
                response_deserializer=submission__pb2.UpdateMaterialValidationResponse.FromString,
                _registered_method=True)


class SubmissionServiceServicer(object):
    """Assessment Submission Service — Validator Agent uses GetMaterials + UpdateMaterialValidation only.
    Full proto at: submission-service/proto/assessorflow/submission/v1/submission.proto
    """

    def GetMaterials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMaterialValidation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubmissionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMaterials': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMaterials,
                    request_deserializer=submission__pb2.GetMaterialsRequest.FromString,
                    response_serializer=submission__pb2.GetMaterialsResponse.SerializeToString,
            ),
            'UpdateMaterialValidation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMaterialValidation,
                    request_deserializer=submission__pb2.UpdateMaterialValidationRequest.FromString,
                    response_serializer=submission__pb2.UpdateMaterialValidationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'assessorflow.submission.v1.SubmissionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('assessorflow.submission.v1.SubmissionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SubmissionService(object):
    """Assessment Submission Service — Validator Agent uses GetMaterials + UpdateMaterialValidation only.
    Full proto at: submission-service/proto/assessorflow/submission/v1/submission.proto
    """

    @staticmethod
    def GetMaterials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assessorflow.submission.v1.SubmissionService/GetMaterials',
            submission__pb2.GetMaterialsRequest.SerializeToString,
            submission__pb2.GetMaterialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMaterialValidation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/assessorflow.submission.v1.SubmissionService/UpdateMaterialValidation',
            submission__pb2.UpdateMaterialValidationRequest.SerializeToString,
            submission__pb2.UpdateMaterialValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
