# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: submission.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'submission.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10submission.proto\x12\x1a\x61ssessorflow.submission.v1\"\xd9\x01\n\x0cMaterialInfo\x12\x13\n\x0bmaterial_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x14\n\x0cstorage_path\x18\x03 \x01(\t\x12\x11\n\tfile_type\x18\x04 \x01(\t\x12\x18\n\x10readiness_status\x18\x05 \x01(\t\x12\x0e\n\x06source\x18\x06 \x01(\t\x12\x12\n\nsource_url\x18\x07 \x01(\t\x12\x1e\n\x16validation_reason_code\x18\x08 \x01(\t\x12\x1a\n\x12validation_message\x18\t \x01(\t\"F\n\x13GetMaterialsRequest\x12\x15\n\rassessment_id\x18\x01 \x01(\t\x12\x18\n\x10unvalidated_only\x18\x02 \x01(\x08\"S\n\x14GetMaterialsResponse\x12;\n\tmaterials\x18\x01 \x03(\x0b\x32(.assessorflow.submission.v1.MaterialInfo\"\xa3\x01\n\x1fUpdateMaterialValidationRequest\x12\x15\n\rassessment_id\x18\x01 \x01(\t\x12\x13\n\x0bmaterial_id\x18\x02 \x01(\t\x12\x18\n\x10readiness_status\x18\x03 \x01(\t\x12\x1e\n\x16validation_reason_code\x18\x04 \x01(\t\x12\x1a\n\x12validation_message\x18\x05 \x01(\t\"a\n UpdateMaterialValidationResponse\x12\x13\n\x0bmaterial_id\x18\x01 \x01(\t\x12\x18\n\x10readiness_status\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2\x9e\x02\n\x11SubmissionService\x12q\n\x0cGetMaterials\x12/.assessorflow.submission.v1.GetMaterialsRequest\x1a\x30.assessorflow.submission.v1.GetMaterialsResponse\x12\x95\x01\n\x18UpdateMaterialValidation\x12;.assessorflow.submission.v1.UpdateMaterialValidationRequest\x1a<.assessorflow.submission.v1.UpdateMaterialValidationResponseB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'submission_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_MATERIALINFO']._serialized_start=49
  _globals['_MATERIALINFO']._serialized_end=266
  _globals['_GETMATERIALSREQUEST']._serialized_start=268
  _globals['_GETMATERIALSREQUEST']._serialized_end=338
  _globals['_GETMATERIALSRESPONSE']._serialized_start=340
  _globals['_GETMATERIALSRESPONSE']._serialized_end=423
  _globals['_UPDATEMATERIALVALIDATIONREQUEST']._serialized_start=426
  _globals['_UPDATEMATERIALVALIDATIONREQUEST']._serialized_end=589
  _globals['_UPDATEMATERIALVALIDATIONRESPONSE']._serialized_start=591
  _globals['_UPDATEMATERIALVALIDATIONRESPONSE']._serialized_end=688
  _globals['_SUBMISSIONSERVICE']._serialized_start=691
  _globals['_SUBMISSIONSERVICE']._serialized_end=977
# @@protoc_insertion_point(module_scope)
